name: telegram_logger
description: A Flutter package for sending error reports and logs to Telegram with optional screenshots. Perfect for debugging and monitoring your Flutter applications.
version: 0.0.2
homepage: https://github.com/nurmuhammad0126/telegram_logger
repository: https://github.com/nurmuhammad0126/telegram_logger
issue_tracker: https://github.com/nurmuhammad0126/telegram_logger/issues
documentation: https://github.com/nurmuhammad0126/telegram_logger#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

topics:
  - telegram
  - logger
  - error-reporting
  - debugging
  - monitoring